# Generated by Django 4.2.1 on 2023-05-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finance',
            options={'verbose_name': 'Finance', 'verbose_name_plural': 'Finances'},
        ),
    ]
