# Generated by Django 4.2.1 on 2023-05-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0003_alter_finance_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
